### Create a new product
@HTTP__BASE_URL = http://127.0.0.1:8000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzA1MTQ5MjU3fQ.bOPqKT9Hu6WHGG1C4hFc47JPJ1ySnEukZJIj6fIDnLE

GET {{HTTP__BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
